import_map.json, live.gen.ts, sections/DesignSystem.tsx, tailwind.config.ts
=> Migrate to tailwind plugin

live.gen.ts, sections/Campanha/Campanha.tsx
=> Testando branch nova

FunctionsSHP/productQntHotsite.ts, components/ComponentsSHP/ProductsCard/CampanhaCard.tsx, live.gen.ts, sections/Campanha/Campanha.tsx, sections/TitleAndText.tsx
Adicionando modificações da pagina de campanha e adicionando section TitleAndText
=> Kauan dev ambient

anotações.txt, components/ComponentsSHP/ProductsCard/CardVtexProdType.tsx
=> Arrumei o preço dos cards

sections/TesteProMaylon.tsx
=> Filtro arrumado pros parça

components/product/ProductCard.tsx, components/search/SearchResult.tsx, import_map.json, sdk/useAddToCart.ts
Eu atualizei o import_map só q tudo q tem o analytics entrou em conflito com tipos, pois o arquivo atualizou e meus componentes com o analitycs são antigos
=> Atualizando o import_map

anotações.txt, components/header/Header.tsx
=> Testando no pc da firma e arrumando img do header

anotações.txt
=> teste dev ambient

components/product/Details.tsx
=> Arrumando parcela na PDP

anotações.txt
=> forçando deploy

components/ui/ShippingSimulation.tsx, import_map.json
=> Calculo de frete corrigido

anotações.txt, components/product/Details.tsx, components/product/NossosNums.tsx
=> Estrelas da PDP linkada com section de review

sections/PagCategEDepto/PagDepartamento.tsx
=> Breadcrumb concertado

components/ComponentsSHP/searchSHP/SearchMenuBar.tsx
=> Arrumei a busca, q na vdd tinha q arrumar no ftp

components/product/BuyBar.tsx, components/product/Details.tsx, loaders/getBuyTogetherValuesBySku.ts
=> Subindo pra testar cadastro do formulário de prod fora do estoque

components/product/Details.tsx
=> subindo pra testart denovo

components/product/Details.tsx
=> teste denovo

components/header/Header.tsx, components/product/Details.tsx
=> Links do Header e formulário de outOfStock funcionando

manifest.gen.ts, sections/Shelf.tsx, sections/Shelf/Filtro.tsx
=> Faltando add funcionabilidade nos filtros

sections/Shelf/Shelf.tsx
=> Arrumando pra n ir filtros vazios

components/product/CompreJunto.tsx
=> Compre junto atrasando a PDP atualizado

components/ComponentsSHP/ProductsCard/ProdFogo.tsx, manifest.gen.ts, sections/EncontreSelectGames.tsx, sections/ImageBackground.tsx
=> Section de backgroundImage criada

anotações.txt, sections/PagCategEDepto/PagDepartamento.tsx
=> Arrumei filtragem pra utilizar o fq de marca ao inves de termo

components/ui/Modal.tsx, fresh.config.ts
=> Removendo top level await

components/ComponentsSHP/searchSHP/SearchMenuBar.tsx, components/header/Header.tsx, components/pop-ups/Help.tsx, sections/Pop-ups/HelperButtons.tsx
=> Arrumando img tags

components/ComponentsSHP/searchSHP/Filtro.tsx, components/ComponentsSHP/searchSHP/Search.tsx, components/ComponentsSHP/searchSHP/SearchSub.tsx, components/footer/Footer.tsx, components/footer/ListSomething.tsx, sections/LPs/Afiliados/Afiliados.tsx, sections/LPs/ParaSuaEmpresa/ParaSuaEmpresa.tsx
=> Alterações de SEO

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, deno.json
=> Atualizando imports e adicionando Docker
